source :rubygems

gem 'rack_csrf', '~> 2.3.0'
gem 'sinatra', '~> 1.3.2'
gem 'sinatra-respond_to', '~> 0.8.0'
gem 'ratpack'
gem 'activesupport', '3.1.3'
gem 'activemodel', '3.1.3'
gem 'supermodel'
gem 'haml'
gem 'pusher'